# -*- coding: utf-8 -*-
token = '363385669:AAHadMpKkzi4bWNeDbTPL-dOZtACtO98CsQ'
tap_to_start = 'I could not understand the meaning of this message. 🙁😔😩 It means that you did something wrong. Please tap on 👉 /start command to begin work with bot again.\n\n' \
				'Мне не удалось распознать смысл этого сообщения. 🙁😔😩 Это означает, что вы сделали что-то неправильно. Нажмите 👉 /start, чтобы начать работать с ботом заново.'
change_lang_eng = 'Change language to 🇷🇺'
change_lang_rus = 'Изменить язык на 🇬🇧'
lang_changed_eng = 'The language has been successfully changed to English 🇬🇧.'
lang_changed_rus = 'Язык успешно изменён на Русский 🇷🇺.'
known_eng = 'I already know you. No need in this command.'
known_rus = 'Я уже знаю тебя. Нет необходимости в этой команде.'
write_mail = 'Enter your mail *@innopolis.ru. We will send there a confirmation message.'
send_confirmation = 'We send to your mail code. Please type this code here and confirm your mail.\n\n' \
					'Мы выслали на вашу почту код. Пожалуйста введите здесь этот код, чтобы подтвердить почту.'
wrong_code = 'Wrong code! Type it again.\n\nНеправильный код! Попробуйте ввести заново.'
repeat_code = 'You have reached the limit of attempts. We have sent to your mail the code again!\n\n' \
				'Вы достигли лимита попыток. Мы отправили на вашу почту код заново.'
wrong_format = 'Wrong format. Try to type your mail again. It should *@innopolis.ru mail.'
contacts_eng = '📞 ✉ Contacts'
contacts_rus = '📞 ✉ Контакты'
list_of_articles_ru = 'Ответ на ваш вопрос может быть найден в одном из этих статей:'
list_of_articles_eng = 'The answer to your question can be found in one of these articles:'
ans_not_found_eng = 'Answer not found'
ans_not_found_rus = 'Не нашёл ответа'
ans_found_eng = 'Answer found'
ans_found_rus = 'Нашёл ответ'
feedback_eng = '⭐ Rate bot'
feedback_rus = '⭐ Оценить бота'
issue_eng = '❓ Ask a question'
issue_rus = '❓ Задать вопрос'
write_issue_eng = 'Write question ⌨ or tap on cancel 👈🏻 button to return to main menu. Also you can send photos and ' \
                  'documents (maximum size is 20 MB).'
write_issue_rus = 'Напишите вопрос ⌨ либо нажмите отмена 👈🏻, чтобы вернуться в основное меню. Также вы можете отправить ' \
                  'фотографии и документы (максимальный размер - 20 МБ).'
cancel_eng = 'Cancel'
cancel_rus = 'Отмена'
operation_cancelled_eng = 'Operation is cancelled'
operation_cancelled_rus = 'Операция отменена.'
tickets_eng = '❓ My questions'
tickets_rus = '❓ Мои вопросы'
tickets_section_eng = 'Here you can see your questions.'
tickets_section_rus = 'Тут вы можете посмотреть свои вопросы.'
all_tickets_eng = 'Show all questions'
all_tickets_rus = 'Показать все вопросы'
closed_tickets_eng = 'Show closed questions'
closed_tickets_rus = 'Показать закрытые вопросы'
opened_tickets_eng = 'Show opened questions'
opened_tickets_rus = 'Показать открытые вопросы'
grade_eng = 'Rate our bot on a 5-point scale:'
grade_rus = 'Оцените нашего бота по 5-бальной шкале:'
write_feedback_eng = 'Write feedback ⌨ or tap on cancel 👈🏻 button to return to main menu.'
write_feedback_rus = 'Напишите отзыв ⌨ либо нажмите отмена 👈🏻, чтобы вернуться в основное меню.'
write_comment_eng = 'Write answer ⌨ or tap on cancel 👈🏻 button to return to main menu. Also you can send photos and ' \
                    'documents (maximum size is 20 MB).'
write_comment_rus = 'Напишите ответ ⌨ либо нажмите отмена 👈🏻, чтобы вернуться в основное меню. Также вы можете ' \
                    'отправить фотографии и документы (максимальный размер - 20 МБ).'
success_feedback_eng = 'Your feedback has been successfully accepted.'
success_feedback_rus = 'Ваш отзыв успешно принят.'
success_comment_rus = 'Ваш ответ успешно отправлен.'
success_comment_eng = 'Your answer has been sent successfully.'
success_question_eng = 'Your question is accepted.'
success_question_rus = 'Ваш вопрос принят.'
success_issue_eng = 'Your question submitted to the IT department of the university for consideration. ' \
                    'Expect the answer. Thank you!'
success_issue_rus = 'Ваш вопрос передан IT-отделу университета на рассмотрение. Ожидайте ответ. Спасибо!'
no_articles_rus = 'Поскольку по Вашему запросу найдено ни одной статьи со стандартным решением проблемы,' \
                  'Ваш вопрос передан IT-отделу университета на рассмотрение. Ожидайте ответ. Спасибо!'
no_articles_eng = 'Since no articles with a standard solution of the problem were found on your request, your question ' \
                  'submitted to the IT department of the university for consideration. Expect the answer. Thank you!'
add_feedback_eng = 'Add feedback'
add_feedback_rus = 'Добавить отзыв'
ticket_assigned_rus = 'Ваш вопрос: {question}, назначен: {name}.\nid диалога: /{id}.'
ticket_assigned_eng = 'Your question: {question}, is assigned: {name}.\nConversation id: /{id}.'
answer_eng = 'Answer to your question: {answer}.\nConversation id: /{id}.'
answer_rus = 'Ответ на ваш вопрос: {answer}.\nid диалога: /{id}.'
ticket_closed_eng = 'The conversation on your question is closed.\nConversation id: /{id}'
ticket_closed_rus = 'Диалог по вашему вопросу закрыт.\nid диалога: /{id}.'
all_conv_eng = 'Your conversations:'
all_conv_rus = 'Ваши диалоги:'
opened_conv_eng = 'Your opened conversations:'
opened_conv_rus = 'Ваши открытые диалоги:'
closed_conv_eng = 'Your closed conversations:'
closed_conv_rus = 'Ваши закрытые диалоги:'
no_dialogue_eng = 'There is no dialogue on this issue.'
no_dialogue_rus = 'По этому вопросу нет диалога.'
no_tickets_eng = 'You have no questions.'
no_tickets_rus = 'У вас нет вопросов.'
no_opened_tickets_eng = 'You have no opened questions.'
no_opened_tickets_rus = 'У вас нет открытых вопросов.'
no_closed_tickets_eng = 'You have no closed questions.'
no_closed_tickets_rus = 'У вас нет закрытых вопросов.'
not_your_question_eng = "You are trying to see someone else's correspondence!"
not_your_question_rus = 'Вы пытаетесь посмотреть чужую переписку!'
send_eng = '📤 Send'
send_rus = '📤 Отправить'
no_text_message_eng = 'You can send only a text feedback. Write something ⌨ or click on cancel 👈🏻.'
no_text_message_rus = 'Можно отправить только текстовый отзыв. Напишите что-нибудь ⌨ или нажмите на отмена 👈🏻.'
att_eng = 'Attachments:'
att_rus = 'Вложения:'
att_one_eng = 'Attachment:'
att_one_rus = 'Вложение:'
happy_eng = 'We are always glad to help you! 😊'
happy_rus = 'Всегда рады вам помочь! 😊'
conver_id_eng = 'Ticket id: /{id}.'
conver_id_rus = 'Ticket id: /{id}.'
question_eng = 'Question: '
question_rus = 'Вопрос: '
send_or_add_rus = 'Вы можете отправить свой вопрос, а можете добавить ещё текста или вложения.'
send_or_add_eng = 'You can send your question, or you can add more text or attachments.'
add_rus = 'Добавить текст/вложение'
add_eng = 'Add text/attachment'
add_more_rus = 'Напишите что-нибудь и оно добавиться к предыдущему тексту. Также можете отправить фото и документы (максимальный размер - 20 МБ).'
add_more_eng = 'Write something and it will be added to the previous text. You can also send photos and documents (maximum size is 20 MB).'
